service: malarcays-api

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  stage: "dev"

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}
    layers:
      - arn:aws:lambda:us-east-1:282315343020:layer:malarcays-api:3

package:
  exclude:
    - node_modules/**
    - node_modules.zip
    - nodejs.zip
    - nodejs/**
    - test/**
    - src/**
