service: malarcays-api

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  stage: "dev"
  region: eu-west-1

functions:
  signup:
    handler: dist/serverless.handler
    events:
      - http:
          path: api/signup
          method: post
          cors: true

  login:
    handler: dist/serverless.handler
    events:
      - http:
          path: api/login
          method: post
          cors: true

  balance:
    handler: dist/serverless.handler
    events:
      - http:
          path: api/balance
          method: get
          cors: true



  main:
    handler: dist/serverless.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}

package:
  exclude:
    - node_modules/**
    - node_modules.zip
    - nodejs.zip
    - nodejs/**
    - test/**
    - src/**
